In [17]:
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [19]:
data = pd.read_csv('rosstat7y.csv') #TRY NEW LAG
X_train = data.iloc[:, 8:200] # без учета года
y_train = data.iloc[:, -1:].values.ravel()
forest = RandomForestClassifier() # n_estimators=400, max_depth=5, n_jobs=-1)

n_estimators = [400]
max_features = ['auto', 'sqrt']
max_depth = [3, 5]
# max_depth.append(None)
# min_samples_split = [2, 5]
# min_samples_leaf = [2, 5]
bootstrap = [True]#, False]

hyper = {'n_estimators': n_estimators, }

grid = GridSearchCV(forest, hyper, cv=5, verbose=1, scoring='roc_auc', n_jobs=-1)
best = grid.fit(X_train, y_train)
print(best.best_estimator_)

Fitting 5 folds for each of 1 candidates, totalling 5 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:  5.2min finished


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=400,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)


In [20]:
best.best_estimator_

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=400,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [25]:
cross_val_score(best.best_estimator_, X_train, y_train, cv=5, scoring = 'roc_auc')

array([0.61996432, 0.69125477, 0.7559069 , 0.75022976, 0.75309525])

In [27]:
cross_val_score(best.best_estimator_, X_train, y_train, cv=5, scoring = 'roc_auc')

array([0.6597217 , 0.67344616, 0.6750364 , 0.72167316, 0.66328495])

In [24]:
importances = best.best_estimator_.feature_importances_
indices = np.argsort(importances)[::-1]
print(X_train.columns[indices][:40])

Index(['56', '32', '80', '42', '70', '36', '40', '78', '84', '82', '116', '28',
       '102', '104', '92', '86', '54', '106', '68', '122', '44', '26', '88',
       '16', '100', '38', '66', '30', '58', '90', '98', '34', '76', '201',
       '114', '20', '200', '96', '199', '108'],
      dtype='object')


In [26]:
data = pd.read_csv('3year_lag.csv') #TRY NEW LAG
X_train = data.iloc[:, 1:-2] #с учетом года
y_train = data.iloc[:, -1:].values.ravel()
forest3year = RandomForestClassifier(n_estimators=400)

In [4]:
cross_val_score(forest3year, X_train, y_train, cv=5, scoring = 'roc_auc') #max

array([0.65626166, 0.66932559, 0.6797032 , 0.71298896, 0.66116928])

In [13]:
# X_train = data.iloc[:, 1:-2] #без учета года
# y_train = data.iloc[:, -1:].values.ravel()
# forest = RandomForestClassifier()
# n_estimators = [int(x) for x in np.linspace(start = 200, stop = 240, num = 10)] # 240 -> 2000
# max_features = ['auto', 'sqrt']
# max_depth = [int(x) for x in np.linspace(10, 40, num = 11)] #40 == 110
# max_depth.append(None)
# min_samples_split = [2, 5, 10]#, 15, 100]
# min_samples_leaf = [1, 2, 5]#, 10] 
# bootstrap = [True]#, False]

# hyper = {'n_estimators': [300],
#                'max_features': max_features,
#                'max_depth': [3],
#                #'min_samples_split': min_samples_split,
#                #'min_samples_leaf': min_samples_leaf,
#                'bootstrap': bootstrap}

# grid = GridSearchCV(forest, hyper, cv = 3, verbose = 1, scoring = 'roc_auc', 
#                       n_jobs = -1)
# best = grid.fit(X_train, y_train)

Fitting 3 folds for each of 2 candidates, totalling 6 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   6 out of   6 | elapsed:   10.6s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   6 out of   6 | elapsed:   10.6s finished
/Users/mikeovyan/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:714: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)
